site_name: База знаний по информационным технологиям

nav:
    - Организационные темы: organisation/README.md
    - Практика: practice/README.md
    - Математика: math/README.md
    - Основы электроники: toe/README.md
    - Информатика: informatics/README.md
    - Администрирование: administration/README.md
    - Программирование: programming/README.md
    - Английский язык: english/README.md
    - Диалоги с нейронкой: dialogs/README.md

site_author:
    p_boyko
