site_name: База знаний по информационным технологиям

nav:
    - Организационные темы: organisation/README.md
    - Теория: theory/README.md
    - Темы по администрированию: administration/README.md
    - Темы по программированию: programming/README.md
    - Математика: math/README.md
    - Английский язык: english/README.md
    - Основы электроники: toe/README.md

site_author:
    p_boyko
